<?php $totalSolicitado=array_sum(array_column($detalle,'total')); ?>
<a class="back-link" href="<?= escapar(url('solicitudes')) ?>">← Volver a solicitudes</a>
<?php if(isset($_GET['guardada']) && $_GET['guardada']==='1'): ?><div class="request-success">✓ Solicitud registrada correctamente y vinculada al Servicio Regional oficial.</div><?php endif; ?>
<?php if(isset($_GET['actualizada']) && $_GET['actualizada']==='1'): ?><div class="request-success">✓ Solicitud actualizada correctamente.</div><?php endif; ?>
<section class="request-detail-hero"><div class="request-detail-folio"><span>Folio de solicitud</span><strong><?= escapar($solicitud['folio']) ?></strong><small><?= escapar($solicitud['fecha_solicitud']) ?></small></div><div class="request-detail-school"><span>Escuela solicitante</span><h3><?= escapar($solicitud['escuela']) ?></h3><p><b><?= escapar($solicitud['cct']) ?></b> · <?= escapar($solicitud['nivel']??'') ?></p><p><?= escapar($solicitud['municipio']??'') ?> · <?= escapar($solicitud['localidad']??'') ?></p></div><div class="request-detail-status"><span>Estado interno</span><strong><?= escapar(str_replace('_',' ',$solicitud['estado'])) ?></strong><small><?= numero($totalSolicitado) ?> uniformes solicitados</small></div></section>
<section class="request-regional-card"><div class="regional-icon">⌂</div><div><span>Destino administrativo oficial</span><h3>Servicio Regional <?= escapar($solicitud['servicio_regional']) ?></h3><p>Esta solicitud se dirige al Servicio Regional indicado por la relación oficial de la escuela.</p></div><div class="request-total"><span>Total solicitado</span><strong><?= numero($totalSolicitado) ?></strong><small>uniformes</small></div></section>
<section class="request-detail-panel"><div class="panel-heading"><div><span>Detalle solicitado</span><h3>Uniformes por talla y género</h3></div><div class="inline-legend"><span class="girl-dot">Niña</span><span class="boy-dot">Niño</span></div></div><div class="request-detail-grid"><?php foreach($detalle as $registro): ?><article class="request-size-card"><div class="request-size-heading"><span>Talla</span><strong><?= escapar($registro['talla']) ?></strong><em><?= numero($registro['total']) ?> piezas</em></div><div class="request-size-values"><div class="girl-value"><span>♀ Niña</span><strong><?= numero($registro['nina']) ?></strong></div><div class="boy-value"><span>♂ Niño</span><strong><?= numero($registro['nino']) ?></strong></div></div></article><?php endforeach; ?></div></section>
<section class="request-scope-note"><strong>Control interno de almacén</strong><span>El estado se actualiza únicamente por personal del sistema para controlar el proceso hacia el Servicio Regional. No representa confirmación ni recepción por parte de la escuela.</span></section>
<?php if(in_array($solicitud['estado'],['PENDIENTE','EN_REVISION','ASIGNADA','EN_PREPARACION'],true)): ?><div class="detail-edit-action"><a class="button" href="<?= escapar(url('solicitud-editar',['id'=>$solicitud['id']])) ?>">Editar solicitud</a><span>Disponible mientras la solicitud no forme parte de un envío.</span></div><?php endif; ?>
