<?php
$disponiblePorTalla=[];
foreach($disponibilidadGeneral as $existencia){
    $disponiblePorTalla[$existencia['sexo']][(int)$existencia['talla_id']]=(int)$existencia['disponible'];
}
?>
<a class="back-link" href="<?= escapar(url('solicitud-detalle',['id'=>$solicitud['id']])) ?>">← Volver al detalle</a>
<?php if($error): ?><div class="notice request-error"><?= escapar($error) ?></div><?php endif; ?>
<section class="edit-request-hero"><div><span>Solicitud editable</span><h3><?= escapar($solicitud['folio']) ?></h3><p><strong><?= escapar($solicitud['escuela']) ?></strong> · <?= escapar($solicitud['cct']) ?></p></div><div><span>Servicio Regional oficial</span><strong><?= escapar($solicitud['servicio_regional']) ?></strong><small>La escuela y el Servicio Regional no se modifican aquí.</small></div></section>
<form method="post" class="request-form"><section class="request-data"><div class="panel-heading"><div><span>Datos de la solicitud</span><h3>Actualizar información</h3></div></div><div class="request-fields"><label>Fecha de solicitud<input type="date" name="fecha_solicitud" value="<?= escapar($solicitud['fecha_solicitud']) ?>" required></label><label>Ciclo o periodo<input type="text" name="ciclo_periodo" maxlength="50" value="<?= escapar($solicitud['ciclo_periodo']??'') ?>"></label><label class="full-field">Observaciones<textarea name="observaciones" maxlength="1000"><?= escapar($solicitud['observaciones']??'') ?></textarea></label></div></section><section class="request-quantities"><div class="panel-heading"><div><span>Detalle editable</span><h3>Cantidades por talla</h3></div><div class="inline-legend"><span class="girl-dot">Niña</span><span class="boy-dot">Niño</span></div></div><div class="request-availability" id="request-availability"><strong>Disponibilidad general de almacenes</strong><span id="request-availability-message">La disponibilidad se revisa con las cantidades actuales de la solicitud.</span></div><div class="quantity-grid"><?php foreach($tallas as $talla): ?><article class="quantity-card"><h4>Talla <?= escapar($talla['talla']) ?></h4><label class="girl-input">♀ Niña<input type="number" name="cantidad[NINA][<?= (int)$talla['id'] ?>]" value="<?= (int)$talla['nina'] ?>" min="0" step="1" inputmode="numeric" data-disponible="<?= (int)($disponiblePorTalla['NINA'][(int)$talla['id']]??0) ?>"><small class="quantity-stock">Disponibles: <?= numero($disponiblePorTalla['NINA'][(int)$talla['id']]??0) ?></small></label><label class="boy-input">♂ Niño<input type="number" name="cantidad[NINO][<?= (int)$talla['id'] ?>]" value="<?= (int)$talla['nino'] ?>" min="0" step="1" inputmode="numeric" data-disponible="<?= (int)($disponiblePorTalla['NINO'][(int)$talla['id']]??0) ?>"><small class="quantity-stock">Disponibles: <?= numero($disponiblePorTalla['NINO'][(int)$talla['id']]??0) ?></small></label></article><?php endforeach; ?></div></section><div class="request-submit"><div><strong>Los cambios no afectan existencias</strong><span>Esta solicitud aún no forma parte de un envío interno.</span></div><button class="button">Guardar cambios</button></div></form>
